# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'foodTruck' do
  # Comment the next line if you're not using Swift and don't want to use dynamic 
  use_frameworks!
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'BraintreeDropIn'
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON'
end
